### ISSUE TITLE
Ajaxify Cart  - Modal 

### ISSUE THREAD

**Issue by strachy** [carolineschnapp/ajaxify-cart#1]
Hi Caroline

I've noticed a problem with the ajaxify modal window - when the scrollbar is visible (add multiple items to cart)  and you click out of the window the modal disappears but the scrollbar remains

it looks like it's just adding a class toggling visibility when clicking the cart - to get around this I've just added the following to ajaxify.scss.css which seems to fix the problem
# ajaxifyModal{display:none;}
# ajaxifyModal.is-visible{display:block;}

Not sure if I'm posting this in the right place - I found this using the timber framework

Thanks
Dave

**Comment by carolineschnapp** [comment]
This isn't the Ajax module from Timber.
