### ISSUE TITLE
Small error when adding single items twice. 

### ISSUE THREAD

**Issue by heymoxie** [carolineschnapp/ajaxify-cart#2]
I'm running into an issue where, if we've got one product in inventory, the first time it's added everything works great.  But the second time, it just says adding forever -- because you can't add something that doesn't exist -- which makes sense on some level.

I've got 422 error popups enabled, based on: http://docs.shopify.com/support/your-store/products/how-to-edit-the-422-cart-error-message-we-do-not-have-x-item-of-y-left
and they perfectly, but the button still reads "adding" after the message is x'ed. 

After digging a little more -- it looks like the error is actually a little later, it's breaking the ajaxify code on the line:

// Re-enable add to cart button and show error message.
            _showFeedback('error', '<i class="fa fa-warning"></i> ' + response.description.replace('All 1 ', 'All '), addToCartForm);

 where 'description' is undefined.

**Comment by carolineschnapp** [comment]
This has been fixed a while back. Feel free to reopen if it hasn't.
