### ISSUE TITLE
Issue with #cartToggle link when duplicated (for hiding on small)

### ISSUE THREAD

**Issue by tdbaylis** [carolineschnapp/ajaxify-cart#4]
When you include the #cartToggle link twice on the page in order to hide one for small+medium and show one for large (using Timber’s classes) the link doesn’t open the modal as expected. Instead both versions direct you straight to the /cart page (no modal.) Removing the duplicate fixes the modal. Not a big deal, but perhaps you could build in support for this?

**Comment by carolineschnapp** [comment]
This solution has no impact on the #cartToggle element. I think you may be confusing this project with Timber's ajax module.
